from types import SimpleNamespace

Config = SimpleNamespace(
    TITLE="API Inference",
    ICON="⚡",
    LAYOUT="wide",
    SERVICES={
        "Huggingface": "https://api-inference.huggingface.co/models",
        "Perplexity": "https://api.perplexity.ai",
        "Fal": "https://fal.run",
    },
    TXT2IMG_HIDDEN_PARAMETERS=[
        "enable_safety_checker",
        "max_sequence_length",
        "num_images",
        "output_format",
        "performance",
        "safety_tolerance",
        "scheduler",
        "sharpness",
        "style",
        "styles",
        "sync_mode",
    ],
    TXT2IMG_NEGATIVE_PROMPT="ugly, unattractive, malformed, mutated, disgusting, blurry, grainy, noisy, oversaturated, undersaturated, overexposed, underexposed, worst quality, low details, lowres, watermark, signature, autograph, trademark, sloppy, cluttered",
    TXT2IMG_DEFAULT_MODEL={
        "Huggingface": 2,
        "Fal": 1,
    },
    TXT2IMG_MODELS={
        "Huggingface": [
            "black-forest-labs/flux.1-dev",
            "black-forest-labs/flux.1-schnell",
            "stabilityai/stable-diffusion-xl-base-1.0",
        ],
        "Fal": [
            # "fal-ai/aura-flow",
            # "fal-ai/flux-pro",
            "fal-ai/fooocus",
            "fal-ai/kolors",
            "fal-ai/pixart-sigma",
            "fal-ai/stable-diffusion-v3-medium",
        ],
    },
    TXT2IMG_DEFAULT_IMAGE_SIZE="square_hd",  # fal image sizes
    TXT2IMG_IMAGE_SIZES=[
        "landscape_16_9",
        "landscape_4_3",
        "square_hd",
        "portrait_4_3",
        "portrait_16_9",
    ],
    TXT2IMG_DEFAULT_ASPECT_RATIO="1024x1024",  # fooocus aspect ratios
    TXT2IMG_ASPECT_RATIOS=[
        "704x1408",
        "704x1344",
        "768x1344",
        "768x1280",
        "832x1216",
        "832x1152",
        "896x1152",
        "896x1088",
        "960x1088",
        "960x1024",
        "1024x1024",
        "1024x960",
        "1088x960",
        "1088x896",
        "1152x896",
        "1152x832",
        "1216x832",
        "1280x768",
        "1344x768",
        "1344x704",
        "1408x704",
        "1472x704",
        "1536x640",
        "1600x640",
        "1664x576",
        "1728x576",
    ],
    TXT2TXT_DEFAULT_SYSTEM="You are a helpful assistant. Be precise and concise.",
    TXT2TXT_DEFAULT_MODEL={
        "Huggingface": 4,
        "Perplexity": 3,
    },
    TXT2TXT_MODELS={
        "Huggingface": [
            "codellama/codellama-34b-instruct-hf",
            "meta-llama/llama-2-13b-chat-hf",
            "meta-llama/meta-llama-3.1-405b-instruct-fp8",
            "mistralai/mistral-7b-instruct-v0.2",
            "nousresearch/nous-hermes-2-mixtral-8x7b-dpo",
        ],
        "Perplexity": [
            "llama-3.1-sonar-small-128k-chat",
            "llama-3.1-sonar-large-128k-chat",
            "llama-3.1-sonar-small-128k-online",
            "llama-3.1-sonar-large-128k-online",
        ],
    },
)
