[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "info"

[client]
# Controls whether uncaught app exceptions and deprecation warnings are displayed in the browser.
# By default, this is set to True and Streamlit displays app exceptions and associated tracebacks,
# and deprecation warnings, in the browser. If set to False, deprecation warnings and full
# exception messages will print to the console only. Exceptions will still display in the browser
# with a generic error message. For now, the exception type and traceback show in the browser also,
# but they will be removed in the future.
# Default: true
showErrorDetails = false

# Change the visibility of items in the toolbar, options menu, and settings dialog (top right of
# the app). Allowed values:
# * "auto" : Show the developer options if the app is accessed through localhost or through Streamlit Community Cloud as a developer. Hide them otherwise.
# * "developer" : Show the developer options.
# * "viewer" : Hide the developer options.
# * "minimal" : Show only options set externally (e.g. through Streamlit Community Cloud) or through st.set_page_config. If there are no options left, hide the menu.
# Default: "auto"
toolbarMode = "viewer"

[runner]
# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
# Default: true
magicEnabled = false

# Raise an exception after adding unserializable data to Session State. Some execution environments
# may require serializing all data in Session State, so it may be useful to detect incompatibility
# during development, or when the execution environment will stop supporting it in the future.
# Default: false
enforceSerializableSessionState = true

[server]
# Change the type of file watcher used by Streamlit, or turn it off completely. Allowed values:
# * "auto" : Streamlit will attempt to use the watchdog module, and falls back to polling if watchdog is not available.
# * "watchdog" : Force Streamlit to use the watchdog module.
# * "poll" : Force Streamlit to always use polling.
# * "none" : Streamlit will not watch files.
# Default: "auto"
fileWatcherType = "auto"

# If false, will attempt to open a browser window on start.
# Default: false unless (1) we are on a Linux box where DISPLAY is unset, or (2) we are running in the Streamlit Atom plugin.
headless = true

# Automatically rerun script when the file is modified on disk.
# Default: false
runOnSave = true

# The address where the server will listen for client and browser connections. Use this if you want
# to bind the server to a specific address. If set, the server will only be accessible from this
# address, and not from any aliases (like localhost).
# Default: (unset)
address = "0.0.0.0"

# The port where the server will listen for browser connections. Don't use port 3000 which is
# reserved for internal development.
# Default: 8501
port = 8501

# The base path for the URL where Streamlit should be served from.
# Default: ""
baseUrlPath = ""

# Enables support for Cross-Origin Resource Sharing (CORS) protection, for added security. Due to
# conflicts between CORS and XSRF, if `server.enableXsrfProtection` is on and `server.enableCORS`
# is off at the same time, we will prioritize `server.enableXsrfProtection`.
# Default: true
enableCORS = true

# Enables support for Cross-Site Request Forgery (XSRF) protection, for added security. Due to
# conflicts between CORS and XSRF, if `server.enableXsrfProtection` is on and `server.enableCORS`
# is off at the same time, we will prioritize `server.enableXsrfProtection`.
# Default: true
enableXsrfProtection = true

# Enable serving files from a `static` directory in the running app's directory.
# Default: false
enableStaticServing = false

[browser]
# Internet address where users should point their browsers in order to connect to the app. Can be
# IP address or DNS name and path. This is used to:
# - Set the correct URL for CORS and XSRF protection purposes.
# - Show the URL on the terminal
# - Open the browser
# Default: "localhost"
serverAddress = "localhost"

# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false
